#!/usr/bin/env ruby
require 'byebug'
require 'io/console'
require_relative 'contact'
require_relative 'phone_numbers'

# Interfaces between a user and their contact list. Reads from and writes to standard I/O.
# Sample query: ruby contact_list.rb show 1 => should display the contact with and ID of 1
class ContactList
  def initialize
  end

  def command_menu
    puts "new    - Create a new contact"
    puts "update - Update an existing contact"
    puts "delete - Delete an existing contact"
    puts "list   - List all contacts"
    puts "show   - Show a contact"
    puts "search - Search contacts"
  end
  
  def paginate_contacts
    Contact.all.each do |contact|
      format_contact(contact)
      format_phone(contact)
    end
    Contact.next_page
   end

  def format_phone(contact)
    contact.phone_numbers.each do |number|
      puts "#{number.label}: #{number.number}"
    end
  end

  def format_contact(contact)
    puts "#{contact.id} #{contact.name}"
    puts "#{contact.email}"
  end
 
  def total_records
    puts "---"
    all_contacts = Contact.connection.exec("SELECT * FROM contacts")
    puts "#{all_contacts.count} records total"
  end

  def add_contact(info)
    name = info.first
    if info.length == 2 
      email = info.last
      Contact.create(name, email)
    else
      email = info[1]
      len = info.length 
      phone = info[2, len]
      Contact.create(name, email, phone)
   end 
  end

  def update_phone(contact)
    contact.phone_numbers.each do |phone|
      puts "Current number: #{phone.label}: #{phone.number}"
      puts "Enter new phone number type:"
      new_label = STDIN.gets
      puts "Enter new phone number:"
      new_number = STDIN.gets
     
      phone.label = new_label
      phone.number = new_number
      phone.save
    end
  end

  def current_contact(id)
    contact = Contact.find(id)
    format_contact(contact)
    format_phone(contact)
  end

  def update_contact(id)
    puts "** CURRENT INFO **"
    current_contact(id)
    
    puts "\nEnter new name:"
    new_name = STDIN.gets
    puts "Enter new email:"
    new_email = STDIN.gets
    
    result = Contact.find(id) 
    result.name = new_name
    result.email = new_email
    
    update_phone(result) #if response.upcase == 'YES'  
    result.save
  end

  def delete_contact(id)
    contact = Contact.find(id[0])
    contact.destroy
  end
  def eval_command(response)
    case response.shift
    when "new"
      add_contact(response)
    when "update"
      id = response.shift.to_i
      update_contact(id)
      puts "\n** UPDATED **"
      current_contact(id)
    when "delete"
      delete_contact(response)
    when "list"
        begin   
        paginate_contacts
        puts "Hit any key to show more"
        STDIN.getch
      end while Contact.rows_left?
      total_records
    when "show"
      id = response.shift.to_i
      current_contact(id)
    when "search"
      term = response.shift
      results = Contact.search(term)
      results.each {|contact| format_contact(contact)} 
    else
      puts "Choose one from the  list of available commands: "
      command_menu
    end
  end
  
  def run
    eval_command(ARGV)
  end 

end

list = ContactList.new
puts list.run
